Problem 4 (WIP)
princerachit/cracking-the-coding-interview-4th-edition pull request #13
Opened 2018-10-04 05:14 UTC by jmhobbs

Closes #10 

Solver is working, but parser is failing on the very large inputs.  Working on sorting that out now.

2018-10-05 05:05 UTC, princerachit requested changes

2018-10-05 05:05 UTC, princerachit commented on others/problem-4/main.go
> +func main() {
please remove main method. All the testing should be done via test files.

2018-10-05 21:27 UTC, jmhobbs commented on others/problem-4/main.go
> +func main() {
I added that to run it on the [hackerearth system](https://www.hackerearth.com/practice/algorithms/dynamic-programming/introduction-to-dynamic-programming-1/practice-problems/algorithm/xsquare-and-two-arrays/).  If you're not concerned with having it work on there than I'll drop `main` and this should be good to go.

2018-10-06 04:06 UTC, princerachit commented on others/problem-4/main.go
> +func main() {
Yeah please drop this.

2018-10-08 14:53 UTC, jmhobbs commented
@princerachit removed the main.  Tests pass, should be good to go 👍

2018-10-08 14:58 UTC, princerachit commented
Thanks for the pr mate. Feel free to create issues and work on them on your own.

2018-10-08 14:58 UTC, merged